version: "3.0"

services:  
    php-apache:
        container_name: 'php-with-apache'
        build: './php'    
        ports:     
            - "80:80"
        volumes:
            - ${DIRECTORY_ROOT}:/var/www/html
